package frc.robot;

public class Constants {

    //swerve stuff is in TunerConstants.java as generated by CTRE

    public double krakenX60kV = (12/6000) ;

    public static final class QuestNavConstants{

    }

    public static final class IndexerConstants {

    }
    public static final class DrivetrainConstants {
        //we might have to put ports in here but IDK
    }
    public static final class IntakeConstants {

    }
    public static final class LauncherConstants {

    }
}
